{{- if .Values.tiles.enabled -}}
{{ $component := "tiles" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "c3nav.fullname" .) $component }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not .Values.tiles.autoscaling.enabled }}
  replicas: {{ .Values.tiles.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "c3nav.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: c3nav-tiles
        checksum/config: {{ include (print $.Template.BasePath "/c3nav-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/c3nav-secret.yaml") . | sha256sum }}
        {{- with .Values.tiles.podExtraAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "c3nav.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "c3nav.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.tiles.podSecurityContext | nindent 8 }}
      containers:
        - name: c3nav-tiles
          securityContext:
            {{- toYaml .Values.tiles.securityContext | nindent 12 }}
          image: {{ include "c3nav.images.tiles" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['web{{ if eq .Values.tiles.mode "asgi" }}-async{{ end }}']
          env:
            - name: K8S_SERVICE_NAME
              value: {{ printf "%s-%s" (include "c3nav.fullname" .) $component | quote }}
            {{- include "c3nav.commonEnvVars" . | nindent 12}}
            - name: UWSGI_WORKERS
              value: {{ .Values.tiles.uwsgiWorkers | quote }}
            - name: C3NAV_SERVE_API
              value: "false"
            {{- if .Values.tiles.extraEnv }}
            {{- .Values.tiles.extraEnv | toYaml | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: c3nav-config
              mountPath: {{ include "c3nav.configPath" . | quote }}
              subPath: {{ include "c3nav.configKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/django_secret
              subPath: {{ include "c3nav.djangoSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/mesh_secret
              subPath: {{ include "c3nav.meshSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/tile_secret
              subPath: {{ include "c3nav.tileSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/hub_api_secret
              subPath: {{ include "c3nav.hubApiSecretKey" . }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath | quote }}
              {{- if and .Values.persistence.enabled (has "ReadWriteMany" .Values.persistence.accessModes) .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath | quote }}
              {{- end }}
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          resources:
            {{- toYaml .Values.tiles.resources | nindent 12 }}
        {{- if and .Values.tiles.metrics.enabled (eq .Values.tiles.mode "wsgi")}}
        - name: metrics
          image: {{ printf "%s/%s:%s" .Values.tiles.metrics.image.registry .Values.tiles.metrics.image.repository .Values.tiles.metrics.image.tag }}
          imagePullPolicy: {{ .Values.tiles.metrics.image.pullPolicy | quote }}
          {{- if .Values.tiles.metrics.securityContext.enabled }}
          securityContext: {{- omit .Values.tiles.metrics.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args: ['--stats.uri', 'http://127.0.0.1:5000/status']
          {{- if .Values.tiles.metrics.extraEnv }}
          env:
            {{- .Values.tiles.metrics.extraEnv | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 30
          {{- if .Values.tiles.metrics.resources }}
          resources: {{- toYaml .Values.tiles.metrics.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: c3nav-config
          configMap:
            name: {{ include "c3nav.configMapName" . }}
        - name: c3nav-secret
          secret:
            secretName: {{ include "c3nav.secretName" . }}
        - name: data
          {{- if and .Values.persistence.enabled (has "ReadWriteMany" .Values.persistence.accessModes) }}
          persistentVolumeClaim:
            claimName: {{ include "c3nav.pvcName" . }}
          {{- else }}
          emptyDir:
            sizeLimit: 4Gi
          {{- end }}
        - name: tmp
          emptyDir:
            sizeLimit: 4Gi
      affinity:
      {{- if .Values.tiles.affinity }}
        {{- toYaml .Values.tiles.affinity | nindent 8 }}
      {{- else }}
        {{- if .Values.tiles.podAntiAffinityPreset }}
        podAntiAffinity:
          {{- if eq .Values.tiles.podAntiAffinityPreset "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- end }}
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "c3nav.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: {{ $component }}
                topologyKey: kubernetes.io/hostname
              weight: 1
        {{- end }}
        {{- if and (not (empty .Values.tiles.nodeAffinityPreset.type)) (not (empty .Values.tiles.nodeAffinityPreset.key)) (not (empty .Values.tiles.nodeAffinityPreset.values)) }}
        nodeAffinity:
          {{- if eq .Values.tiles.nodeAffinityPreset.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- end }}
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.tiles.nodeAffinityPreset.key }}
                    operator: In
                    values:
                      {{- toYaml .Values.tiles.nodeAffinityPreset.values | nindent 22 }}
        {{- end }}
      {{- end }}
      {{- with .Values.tiles.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tiles.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
