{{ $component := "workers" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "c3nav.fullname" .) $component }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not .Values.workers.autoscaling.enabled }}
  replicas: {{ .Values.workers.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "c3nav.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: c3nav-workers
        checksum/config: {{ include (print $.Template.BasePath "/c3nav-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/c3nav-secret.yaml") . | sha256sum }}
        {{- with .Values.workers.podExtraAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "c3nav.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "c3nav.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.workers.podSecurityContext | nindent 8 }}
      containers:
        - name: c3nav-workers
          securityContext:
            {{- toYaml .Values.workers.securityContext | nindent 12 }}
          image: {{ printf "%s/%s:%s" .Values.image.registry (default .Values.image.coreRepository .Values.image.workersRepository) (default .Chart.AppVersion .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker"]
          env:
            - name: K8S_SERVICE_NAME
              value: {{ printf "%s-%s" (include "c3nav.fullname" .) $component | quote }}
            {{- include "c3nav.commonEnvVars" . | nindent 12}}
            {{- if .Values.workers.extraEnv }}
            {{- .Values.workers.extraEnv | toYaml | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: c3nav-config
              mountPath: {{ include "c3nav.configPath" . | quote }}
              subPath: {{ include "c3nav.configKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/django_secret
              subPath: {{ include "c3nav.djangoSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/mesh_secret
              subPath: {{ include "c3nav.meshSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/tile_secret
              subPath: {{ include "c3nav.tileSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/hub_api_secret
              subPath: {{ include "c3nav.hubApiSecretKey" . }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath | quote }}
              {{- if and .Values.persistence.enabled (has "ReadWriteMany" .Values.persistence.accessModes) .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath | quote }}
              {{- end }}
            - name: cache
              mountPath: /cache
          livenessProbe:
            exec:
              command:
                - entrypoint
                - worker_healthcheck
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 2
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      volumes:
        - name: c3nav-config
          configMap:
            name: {{ include "c3nav.configMapName" . }}
        - name: c3nav-secret
          secret:
            secretName: {{ include "c3nav.secretName" . }}
        - name: data
          {{- if and .Values.persistence.enabled (has "ReadWriteMany" .Values.persistence.accessModes) }}
          persistentVolumeClaim:
            claimName: {{ include "c3nav.pvcName" . }}
          {{- else }}
          emptyDir:
            sizeLimit: 4Gi
          {{- end }}
        - name: cache
          emptyDir:
            sizeLimit: 1Gi
      affinity:
      {{- if .Values.workers.affinity }}
        {{- toYaml .Values.workers.affinity | nindent 8 }}
      {{- else }}
        {{- if .Values.workers.podAntiAffinityPreset }}
        podAntiAffinity:
          {{- if eq .Values.workers.podAntiAffinityPreset "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- end }}
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "c3nav.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: {{ $component }}
                topologyKey: kubernetes.io/hostname
              weight: 1
        {{- end }}
        {{- if and (not (empty .Values.workers.nodeAffinityPreset.type)) (not (empty .Values.workers.nodeAffinityPreset.key)) (not (empty .Values.workers.nodeAffinityPreset.values)) }}
        nodeAffinity:
          {{- if eq .Values.workers.nodeAffinityPreset.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulungIgnoredDuringExecution:
          {{- end }}
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.workers.nodeAffinityPreset.key }}
                    operator: In
                    values:
                      {{- toYaml .Values.workers.nodeAffinityPreset.values | nindent 22 }}
        {{- end }}
      {{- end }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
