{{- if empty .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav-tileserver.secretName" . }}
  labels:
    {{- include "c3nav-tileserver.labels" . | nindent 4 }}
data:
  {{ include "c3nav-tileserver.tileSecretKey" . }}: {{ required "c3nav.tile_secret must be set unless existingSecret is used." .Values.c3nav.tile_secret | b64enc | quote }}
  {{- if or .Values.c3nav.httpAuth.username .Values.c3nav.httpAuth.password }}
  {{- with .Values.c3nav.httpAuth }}
  {{ include "c3nav-tileserver.httpAuthKey" $ }}: {{ (printf "%s:%s" .username .password) | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}