{{- if and (eq .Values.ingress.className "traefik") .Values.ingress.basicAuth (empty .Values.ingress.existingBasicAuthSecret) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "c3nav-tileserver.traeficBasicAuthMiddlewareName" . }}
  labels:
    {{- include "c3nav-tileserver.labels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "c3nav-tileserver.traeficBasicAuthSecretName" . }}
    realm: {{ if not (contains "c3nav" .Values.c3nav.name) }}c3nav {{ end }}{{ .Values.c3nav.name }}
    removeHeader: true
{{- end }}