apiVersion: v2
name: c3nav
description: c3nav - indoor navigation for events
home: https://c3nav.de
icon: https://c3nav.de/assets/helm/icon.png
maintainers:
  - name: Jenny Danzmayr
    email: mail@evilscientress.de
annotations:
  category: Webapps
  licenses: Apache-2.0
sources:
  - "https://github.com/c3nav/c3nav-charts"
dependencies:
  - name: postgresql
    version: 16.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 20.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: memcached
    version: 7.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: memcached.enabled


type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# currently c3nav doesn't have releases. Until this changes we use commit hashes as the app version.
appVersion: "38c705717b969c6b36fc4521e82d5226aa76edd9"
