apiVersion: v2
name: c3nav
description: c3nav - indoor navigation for events
home: https://c3nav.de
icon: https://c3nav.de/assets/helm/icon.png
maintainers:
  - name: Jenny Danzmayr
    email: mail@evilscientress.de
annotations:
  category: Webapps
  licenses: Apache-2.0
sources:
  - "https://github.com/c3nav/c3nav-charts"
dependencies:
  - name: postgresql
    version: 13.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: 18.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: memcached
    version: 6.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: memcached.enabled


type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.27

# currently c3nav doesn't have releases. Until this changes we use commit hashes as the app version.
appVersion: "c7bf7d6b8b947c2b46ceb6459727de2d23121bc4"
