apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-static" (include "c3nav.fullname" .) }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
    app.kubernetes.io/component: static
data:
  nginx.conf: |
    {{- if empty .Values.static.nginxConfig }}
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf 
    # user              www www;  ## Default: nobody
    
    worker_processes  auto; 
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";
    
    load_module modules/ngx_http_brotli_filter_module.so;
    load_module modules/ngx_http_brotli_static_module.so;
    
    events {      
        worker_connections  1024;
    }               
                                                                                          
    http {            
        include       mime.types;                                                         
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log" main;
        add_header    X-Frame-Options SAMEORIGIN;
    
        client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
        proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
        fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
        scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
        uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;
    
        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;   
        gzip_proxied       any;
        gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers        HIGH:!aNULL:!MD5;
        client_max_body_size 80M;
        server_tokens off;
    
        absolute_redirect  off;      
        port_in_redirect   off;    
    
        brotli on; 
        brotli_comp_level 6;
        brotli_static on;              
        brotli_types application/atom+xml application/javascript application/json application/vnd.api+json application/rss+xml
                     application/vnd.ms-fontobject application/x-font-opentype application/x-font-truetype
                     application/x-font-ttf application/x-javascript application/xhtml+xml application/xml
                     font/eot font/opentype font/otf font/truetype image/svg+xml image/vnd.microsoft.icon
                     image/x-icon image/x-win-bitmap text/css text/javascript text/plain text/xml;
    
        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
    
        # HTTP Server
        server {       
            # Port to listen on, can also be set in IP:PORT format
            listen 8080;
    
            root /app;                 
                                                                                                                                                                                    
            include  "/opt/bitnami/nginx/conf/bitnami/*.conf";
                                                                                                                                                                                    
            location /status {
                stub_status on;
                access_log   off;
                allow 127.0.0.1;
                deny all;
            }
        }
        {{- if (.Values.static.nginxConfigExtra | default "") }}
        {{- .Values.static.nginxConfigExtra | nindent 8 }}
        {{- end }}
    }
    {{- else }}
    {{- .Values.static.nginxConfig | nindent 4 }}
    {{- end }}
