{{- if empty .Values.existingC3navSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.secretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
data:
  {{ include "c3nav.djangoSecretKey" . }}: {{ include "c3nav.djangoSecret" .  | quote }}
  {{ include "c3nav.tileSecretKey" . }}: {{ include "c3nav.tileSecret" .  | quote }}
  {{ include "c3nav.memcachedKey" .}}: {{ include "c3nav.memcachedConnection" .  | quote }}
  {{ include "c3nav.redisKey" . }}: {{ include "c3nav.redisConnection" .  | quote }}
  {{ include "c3nav.redisPasswordKey" . }}: {{ include "c3nav.redisPassword" .  | quote }}
  {{ include "c3nav.celeryBrokerKey" . }}: {{ include "c3nav.celeryBroker" .  | quote }}
  {{ include "c3nav.celeryBackendKey" . }}: {{ include "c3nav.celeryBackend" .  | quote }}
{{- end }}