{{- if empty .Values.existingC3navConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.configSecretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
stringData:
  c3nav.cfg: |2
    {{- if .Values.c3navConfig }}
    {{ .Values.c3navConfig | nindent 4 }}
    {{- else }}
    [c3nav]
    {{- range $key, $value := omit .Values.c3nav "database" "urls" "django" "locale" "mail" "memcached" "redis" "celery" }}
    {{- if and $value (not (kindIs "map" $value)) }}
    {{ include "c3nav.toIniLine" (dict "key" $key "value" $value) }}
    {{- end }}
    {{- end }}
    [database]
    [django]
    secret={{ include "c3nav.djangoSecret" . }}
    {{- range $key, $value := omit .Values.c3nav.django "hosts" "secret" }}
    {{- if and $value (not (kindIs "map" $value)) }}
    {{ include "c3nav.toIniLine" (dict "key" $key "value" $value) }}
    {{- end }}
    {{- end }}
    {{- range $sectionName, $section := pick .Values.c3nav "memcached" "redis" }}
    {{- if $section.location }}
    [{{ $sectionName }}]
    {{- range $key, $value := $section }}
    {{ include "c3nav.toIniLine" (dict "key" $key "value" $value) }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- range $sectionName, $section := omit .Values.c3nav "database" "django" "memcached" "redis" }}
    {{- if kindIs "map" $section }}
    [{{ $sectionName }}]
    {{- range $key, $value := $section }}
    {{- if $value }}
    {{ include "c3nav.toIniLine" (dict "key" $key "value" $value) }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

{{- end }}