{{- if empty .Values.existingC3navConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c3nav.configMapName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
data:
  {{ include "c3nav.configKey" . }}: |2
    {{- if .Values.c3navConfig }}
    {{- .Values.c3navConfig | nindent 4 }}
    {{- else }}
    [c3nav]
    {{- include "c3nav.toIniSection" (dict "section" (omit .Values.c3nav "name" "debug" "loglevel" "memcached" "redis" "mesh_secret" "tile_secret") "root" $) | nindent 4 }}
    [django]
    {{- include "c3nav.toIniSection" (dict "section" (omit .Values.c3nav.django "hosts" "secret") "root" $) | nindent 4 }}
    {{- range $sectionName, $section := omit .Values.c3nav "django" "database" "email" "memcached" "redis" "celery" }}
    {{- if kindIs "map" $section }}
    [{{ $sectionName }}]
    {{- include "c3nav.toIniSection" (dict "section" $section "root" $) | nindent 4 }}
    {{- end }}
    {{- end }}
    {{- if .Values.c3navConfigExtra }}
    {{- .Values.c3nav.ConfigExtra | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}