{{- if empty .Values.existingC3navSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.secretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
data:
  {{ include "c3nav.djangoSecretKey" . }}: {{ include "c3nav.djangoSecret" . | b64enc | quote }}
  {{ include "c3nav.tileSecretKey" . }}: {{ include "c3nav.tileSecret" . | b64enc | quote }}
  {{ include "c3nav.memcachedKey" .}}: {{ include "c3nav.memcachedConnection" . | b64enc | quote }}
  {{ include "c3nav.redisPasswordKey" . }}: {{ include "c3nav.redisPassword" . | b64enc | quote }}
  {{ include "c3nav.redisKey" . }}: {{ include "c3nav.redisConnection" . | b64enc | quote }}
  {{ include "c3nav.celeryBrokerKey" . }}: {{ include "c3nav.celeryBroker" . | b64enc | quote }}
  {{ include "c3nav.celeryBackendKey" . }}: {{ include "c3nav.celeryBackend" . | b64enc | quote }}
  {{ include "c3nav.emailUserKey" . }}: {{ .Values.c3nav.email.user | b64enc | quote }}
  {{ include "c3nav.emailPasswordKey" . }}: {{ .Values.c3nav.email.password | b64enc | quote }}
{{- end }}