{{- if and (empty .Values.existingDatabaseSecret) (not .Values.postgresql.enabled) (ne (include "c3nav.secretName" .) (include "c3nav.databaseSecretName" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.databaseSecretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
data:
  {{include "databasePasswordKey" . }}: {{ .Values.c3nav.database.password | b64enc | quote}}
{{- end }}