{{- if and (empty .Values.existingMemcachedSecret) .Values.memcached.enabled .Values.memcached.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.memcachedSecretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
data:
  memcached-password: {{ include "c3nav.memcachedPassword" . | b64enc | quote}}
{{- end }}