{{- if and (eq .Values.ingress.className "traefik") .Values.ingress.basicAuth (empty .Values.ingress.existingBasicAuthSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c3nav.traeficBasicAuthSecretName" . }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
stringData:
  users: |2
    {{- range $username, $password := .Values.ingress.basicAuth }}
    {{- if or (hasPrefix "$apr1$" $password) (hasPrefix "{SHA}" $password) (regexMatch "^\\$2[abxy]\\$.*$" $password) }}
    {{ $username }}:{{ $password }}
    {{- else }}
    {{ htpasswd $username $password }}
    {{- end }}
    {{- end }}
{{- end }}