{{ $component := "core" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "c3nav.fullname" .) $component }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not .Values.core.autoscaling.enabled }}
  replicas: {{ .Values.core.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "c3nav.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      {{- with .Values.core.podExtraAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "c3nav.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "c3nav.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.core.podSecurityContext | nindent 8 }}
      containers:
        - name: c3nav-core
          securityContext:
            {{- toYaml .Values.core.securityContext | nindent 12 }}
          image: {{ include "c3nav.images.core" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['{{ if .Values.static.enabled }}web{{ else }}webstatic{{ end }}']
          env:
            - name: K8S_SERVICE_NAME
              value: {{ printf "%s-%s" (include "c3nav.fullname" .) $component | quote }}
            {{- include "c3nav.commonEnvVars" . | nindent 12}}
            - name: UWSGI_WORKERS
              value: {{ .Values.core.uwsgiWorkers | quote }}
          volumeMounts:
            - name: c3nav-config
              mountPath: {{ include "c3nav.configPath" . | quote }}
              subPath: {{ include "c3nav.configKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/django_secret
              subPath: {{ include "c3nav.djangoSecretKey" . }}
            - name: c3nav-secret
              mountPath: /etc/c3nav/tile_secret
              subPath: {{ include "c3nav.tileSecretKey" . }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
        {{- if .Values.core.metrics.enabled }}
        - name: metrics
          image: {{ include "c3nav.images.core_metrics" . }}
          imagePullPolicy: {{ .Values.core.metrics.image.pullPolicy | quote }}
          {{- if .Values.core.metrics.securityContext.enabled }}
          securityContext: {{- omit .Values.core.metrics.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args: ['--stats.uri', 'http://127.0.0.1:5000/status']
          ports:
            - name: metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- if .Values.core.metrics.resources }}
          resources: {{- toYaml .Values.core.metrics.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: c3nav-config
          configMap:
            name: {{ include "c3nav.configMapName" . }}
        - name: c3nav-secret
          secret:
            secretName: {{ include "c3nav.secretName" . }}
      affinity:
      {{- if .Values.core.affinity }}
        {{- toYaml .Values.core.affinity | nindent 8 }}
      {{- else }}
        {{- if .Values.core.podAntiAffinityPreset }}
        podAntiAffinity:
          {{- if eq .Values.core.podAntiAffinityPreset "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- end }}
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "c3nav.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: {{ $component }}
                topologyKey: kubernetes.io/hostname
              weight: 1
        {{- end }}
        {{- if and (not (empty .Values.core.nodeAffinityPreset.type)) (not (empty .Values.core.nodeAffinityPreset.key)) (not (empty .Values.core.nodeAffinityPreset.values)) }}
        nodeAffinity:
          {{- if eq .Values.core.nodeAffinityPreset.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- else }}
          preferredDuringSchedulungIgnoredDuringExecution:
          {{- end }}
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.core.nodeAffinityPreset.key }}
                    operator: In
                    values:
                      {{- toYaml .Values.core.nodeAffinityPreset.values | nindent 22 }}
        {{- end }}
      {{- end }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
