apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-core" (include "c3nav.fullname" .) }}
  labels:
    {{- include "c3nav.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - name: http
      port: {{ .Values.core.service.port }}
      targetPort: http
    {{- if .Values.core.metrics.enabled }}
    - name: metrics
      port: {{ .Values.core.metrics.service.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "c3nav.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
